server:
  port: ${PORT:8888}

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juanmorales9/BackEndParcial
          force-pull: true
          search-paths: ConfigData